/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boutique.ui;

/**
 *
 * @author X1 YOGA
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainForm() {
        initComponents();
        this.setTitle("Gestion Boutique");
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        ProduitMenuItem = new javax.swing.JMenuItem();
        ClientMenuItem = new javax.swing.JMenuItem();
        VenteProduitMenuItem = new javax.swing.JMenuItem();
        menuStatistiques = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        SearchByCategorieMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        ProduitMenuItem.setMnemonic('o');
        ProduitMenuItem.setText("Produit");
        ProduitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProduitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(ProduitMenuItem);

        ClientMenuItem.setMnemonic('s');
        ClientMenuItem.setText("Client");
        ClientMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(ClientMenuItem);

        VenteProduitMenuItem.setText("Vente");
        VenteProduitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenteProduitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(VenteProduitMenuItem);

        menuStatistiques.setText("Statistiques");
        menuStatistiques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStatistiquesActionPerformed(evt);
            }
        });
        fileMenu.add(menuStatistiques);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Recherche");

        SearchByCategorieMenuItem.setMnemonic('t');
        SearchByCategorieMenuItem.setText("SearchByCategorie");
        SearchByCategorieMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchByCategorieMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(SearchByCategorieMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void ProduitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProduitMenuItemActionPerformed
        // TODO add your handling code here:
        ProduitForm ff = new ProduitForm();
        desktopPane.add(ff);
        ff.setVisible(true);
    }//GEN-LAST:event_ProduitMenuItemActionPerformed

    private void ClientMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientMenuItemActionPerformed
        // TODO add your handling code here:
        ClientForm ef = new ClientForm();
        desktopPane.add(ef);
        ef.setVisible(true);
    }//GEN-LAST:event_ClientMenuItemActionPerformed

    private void SearchByCategorieMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchByCategorieMenuItemActionPerformed
        // TODO add your handling code here:
      RechercheForm rechercheForm = new RechercheForm();
    desktopPane.add(rechercheForm);
    rechercheForm.setVisible(true);
    }//GEN-LAST:event_SearchByCategorieMenuItemActionPerformed

    private void VenteProduitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenteProduitMenuItemActionPerformed
        VenteForm ef = new VenteForm();
        desktopPane.add(ef);
        ef.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_VenteProduitMenuItemActionPerformed

    private void menuStatistiquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStatistiquesActionPerformed
        // TODO add your handling code here:
        Statistiques stats = new Statistiques();
    desktopPane.add(stats);
    stats.setVisible(true);
    }//GEN-LAST:event_menuStatistiquesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Auth().setVisible(true);
                //new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ClientMenuItem;
    private javax.swing.JMenuItem ProduitMenuItem;
    private javax.swing.JMenuItem SearchByCategorieMenuItem;
    private javax.swing.JMenuItem VenteProduitMenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuStatistiques;
    // End of variables declaration//GEN-END:variables

}
