/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boutique.ui;
import boutique.entities.Produit;
import boutique.services.ProduitService;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author hp
 */
public class ProduitForm extends javax.swing.JInternalFrame {
private ProduitService ProduitService = new ProduitService();

    /**
     * Creates new form ProduitFrame
     */
    public ProduitForm() {
        initComponents();
        setTitle("Gestion des Produits");
        comboCategorie.addItem("Informatique");
        comboCategorie.addItem("Accessoire");
        comboCategorie.addItem("Electromenager");
        Dimension btnSize = new Dimension(120, 35);

        btnAjouter.setPreferredSize(btnSize);
        btnModifier.setPreferredSize(btnSize);
        btnSupprimer.setPreferredSize(btnSize);
        btnVider.setPreferredSize(btnSize);
        btnRetour.setPreferredSize(btnSize);


         loadTable();
    }
private void loadTable() {
    DefaultTableModel model = (DefaultTableModel) tableProduits.getModel();
    model.setRowCount(0);

    List<Produit> produits = ProduitService.findAll();
    System.out.println("Produits trouvés = " + produits.size()); 

    for (Produit p : produits) {
        System.out.println("Produit: " + p.getLibelle()); 
        model.addRow(new Object[]{
            p.getIdProduit(),
            p.getLibelle(),
            p.getPrix(),
            p.getStock(),
            p.getCategorie()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane2 = new javax.swing.JScrollPane();
        tableProduits = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtIdProduit = new javax.swing.JTextField();
        lblIdProduit = new javax.swing.JLabel();
        txtLibelle = new javax.swing.JTextField();
        lblLibelle = new javax.swing.JLabel();
        txtPrix = new javax.swing.JTextField();
        lblPrix = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        lblCategorie = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboCategorie = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnVider = new javax.swing.JButton();
        btnRetour = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tableProduits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Produit", "Libelle", "Prix", "Stock", "Categorie"
            }
        ));
        tableProduits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProduitsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableProduits);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 20, 15, 34);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        txtIdProduit.setEditable(false);
        txtIdProduit.setName(""); // NOI18N

        lblIdProduit.setText("IdProduit  :");

        lblLibelle.setText("Libelle :");

        lblPrix.setText("Prix :");

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });

        lblStock.setText("Stock :");

        lblCategorie.setText("Categorie :");

        jLabel2.setText("Formulaire :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStock)
                            .addComponent(lblCategorie))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(txtPrix))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboCategorie, 0, 306, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStock))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdProduit)
                            .addComponent(lblLibelle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtLibelle)
                                .addGap(13, 13, 13))
                            .addComponent(txtIdProduit))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdProduit))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLibelle)
                            .addComponent(txtLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrix))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(lblStock))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategorie)
                    .addComponent(comboCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 65;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnAjouter.setBackground(new java.awt.Color(70, 130, 180));
        btnAjouter.setText("Ajouter");
        btnAjouter.setFocusPainted(false);
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 63);
        jPanel3.add(btnAjouter, gridBagConstraints);

        btnModifier.setText("Modifier");
        btnModifier.setActionCommand("");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 12, 0, 63);
        jPanel3.add(btnModifier, gridBagConstraints);

        btnVider.setText("Vider");
        btnVider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViderActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 12, 0, 63);
        jPanel3.add(btnVider, gridBagConstraints);

        btnRetour.setText("Retour");
        btnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 12, 11, 63);
        jPanel3.add(btnRetour, gridBagConstraints);

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 12, 0, 63);
        jPanel3.add(btnSupprimer, gridBagConstraints);

        jLabel1.setText("Actions :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 10, 0, 0);
        jPanel3.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 0);
        getContentPane().add(jPanel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableProduitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProduitsMouseClicked
        int row = tableProduits.getSelectedRow();

        txtIdProduit.setText(tableProduits.getValueAt(row, 0).toString());
        txtLibelle.setText(tableProduits.getValueAt(row, 1).toString());
        txtPrix.setText(tableProduits.getValueAt(row, 2).toString());
        txtStock.setText(tableProduits.getValueAt(row, 3).toString());

        comboCategorie.setSelectedItem(tableProduits.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tableProduitsMouseClicked

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
       Produit p = new Produit();
    p.setLibelle(txtLibelle.getText());
    p.setPrix(Double.parseDouble(txtPrix.getText()));
    p.setStock(Integer.parseInt(txtStock.getText()));
    p.setCategorie(comboCategorie.getSelectedItem().toString());

    ProduitService.create(p);
    loadTable();
    }//GEN-LAST:event_txtStockActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        String lib = txtLibelle.getText().trim();
        String prixTxt = txtPrix.getText().trim();
        String stockTxt = txtStock.getText().trim();

        if (lib.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Libellé obligatoire !");
            return;
        }
        if (comboCategorie.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Choisissez une catégorie !");
            return;
        }

        double prix;
        int stock;

        try {
            prix = Double.parseDouble(prixTxt);
            stock = Integer.parseInt(stockTxt);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Prix ou stock invalide !");
            return;
        }

        if (prix <= 0) {
            JOptionPane.showMessageDialog(this, "Le prix doit être > 0 !");
            return;
        }
        if (stock < 0) {
            JOptionPane.showMessageDialog(this, "Le stock doit être >= 0 !");
            return;
        }

        try {
            Produit p = new Produit();
            p.setLibelle(lib);
            p.setPrix(prix);
            p.setStock(stock);
            p.setCategorie(comboCategorie.getSelectedItem().toString());

            ProduitService.create(p);

            JOptionPane.showMessageDialog(this, "Produit ajouté avec succès !");
            loadTable();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout : " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed

        int row = tableProduits.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Sélectionnez un produit dans la table !");
            return;
        }

        String lib = txtLibelle.getText().trim();
        String prixTxt = txtPrix.getText().trim();
        String stockTxt = txtStock.getText().trim();

        if (lib.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Libellé obligatoire !");
            return;
        }
        if (comboCategorie.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Choisissez une catégorie !");
            return;
        }

        double prix;
        int stock;
        try {
            prix = Double.parseDouble(prixTxt);
            stock = Integer.parseInt(stockTxt);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Prix ou stock invalide !");
            return;
        }

        if (prix <= 0) {
            JOptionPane.showMessageDialog(this, "Le prix doit être > 0 !");
            return;
        }
        if (stock < 0) {
            JOptionPane.showMessageDialog(this, "Le stock doit être >= 0 !");
            return;
        }

        int id = Integer.parseInt(tableProduits.getValueAt(row, 0).toString());

        try {
            Produit p = new Produit();
            p.setIdProduit(id);
            p.setLibelle(lib);
            p.setPrix(prix);
            p.setStock(stock);
            p.setCategorie(comboCategorie.getSelectedItem().toString());

            ProduitService.update(p);
            loadTable();
            JOptionPane.showMessageDialog(this, "Produit modifié !");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur lors de la modification : " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnViderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViderActionPerformed
        txtIdProduit.setText("");
        txtLibelle.setText("");
        txtPrix.setText("");
        txtStock.setText("");

        comboCategorie.setSelectedIndex(0);

        tableProduits.clearSelection();

    }//GEN-LAST:event_btnViderActionPerformed

    private void btnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourActionPerformed
        MainForm mf = new MainForm();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRetourActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        int row = tableProduits.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Sélectionnez un produit dans la table !");
            return;
        }

        int id = Integer.parseInt(tableProduits.getValueAt(row, 0).toString());

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Voulez-vous vraiment supprimer ce produit ?",
            "Confirmation",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            ProduitService.delete(id);  
            loadTable();
            JOptionPane.showMessageDialog(this, "Produit supprimé !");
        }

    }//GEN-LAST:event_btnSupprimerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnRetour;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnVider;
    private javax.swing.JComboBox comboCategorie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCategorie;
    private javax.swing.JLabel lblIdProduit;
    private javax.swing.JLabel lblLibelle;
    private javax.swing.JLabel lblPrix;
    private javax.swing.JLabel lblStock;
    private javax.swing.JTable tableProduits;
    private javax.swing.JTextField txtIdProduit;
    private javax.swing.JTextField txtLibelle;
    private javax.swing.JTextField txtPrix;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
