/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boutique.ui;
import boutique.entities.Vente;
import boutique.entities.Client;
import boutique.entities.Produit;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
/**
 *
 * @author Lenovo
 */
public class RechercheForm extends javax.swing.JInternalFrame {
private boutique.services.VenteService venteService = new boutique.services.VenteService();
private boutique.services.ClientService clientService = new boutique.services.ClientService();
private boutique.services.ProduitService produitService = new boutique.services.ProduitService();
    /**
     * Creates new form RechercheForm
     */
    public RechercheForm() {
        initComponents();
         jTable2.setFillsViewportHeight(true);           // Remplit la hauteur
    jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS); // Redimensionne les colonnes
        
// VIDER COMPLÈTEMENT LA COMBOBOX (méthode radicale)
    jComboBox1.removeAllItems();
    
    // ACTIONS DES BOUTONS
    jButton1.addActionListener(evt -> btnFiltrerActionPerformed(evt));
    jButton2.addActionListener(evt -> btnReinitialiserActionPerformed(evt));
    
    // 3️⃣ INITIALISER LES DATES
    jSpinner1.setValue(new java.util.Date());
    java.util.Calendar cal = java.util.Calendar.getInstance();
    cal.add(java.util.Calendar.DAY_OF_MONTH, 30);
    jSpinner2.setValue(cal.getTime());
    
    // CHARGER LES CATÉGORIES
    chargerCategories();
    
    // TAILLE DE LA FENÊTRE
    this.setSize(900, 600);
    this.validate();
    this.repaint();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Catégorie :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 18, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Toutes", "Accessoire", "Informatique", "Electroménager" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 0, 0);
        getContentPane().add(jComboBox1, gridBagConstraints);

        jLabel2.setText("Du :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 13, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jSpinner1.setModel(new javax.swing.SpinnerDateModel());
        jSpinner1.setEditor(new javax.swing.JSpinner.DateEditor(jSpinner1, "dd/MM/yyyy"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 0, 0);
        getContentPane().add(jSpinner1, gridBagConstraints);

        jLabel3.setText("Au :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 39, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jSpinner2.setModel(new javax.swing.SpinnerDateModel());
        jSpinner2.setEditor(new javax.swing.JSpinner.DateEditor(jSpinner2, "dd/MM/yyyy"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 0, 0);
        getContentPane().add(jSpinner2, gridBagConstraints);

        jButton1.setText("Filtrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 66, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        jButton2.setText("Réinitialiser");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 4, 0, 0);
        getContentPane().add(jButton2, gridBagConstraints);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdVente", "DateVente", "Client", "Produit", "Quantité"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 484;
        gridBagConstraints.ipady = 146;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Forcer un modèle vide
    
   private void chargerCategories() {
    try {
        // VIDER AVANT DE REMPLIR (sécurité)
        jComboBox1.removeAllItems();
        
        // AJOUTER "Toutes"
        jComboBox1.addItem("Toutes");
        
        // AJOUTER LES CATÉGORIES DE LA BASE
        List<String> categories = produitService.getAllCategories();
        for (String cat : categories) {
            // Éviter les doublons avec "Toutes"
            if (!cat.equals("Toutes")) {
                jComboBox1.addItem(cat);
            }
        }
        
        // SI AUCUNE CATÉGORIE, AJOUTER DES DÉFAUTS
        if (jComboBox1.getItemCount() <= 1) {
            jComboBox1.addItem("Accessoire");
            jComboBox1.addItem("Informatique");
            jComboBox1.addItem("Électroménager");
        }
        
    } catch (Exception e) {
        e.printStackTrace();
        // EN CAS D'ERREUR, AJOUTER DES DÉFAUTS
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Toutes");
        jComboBox1.addItem("Accessoire");
        jComboBox1.addItem("Informatique");
        jComboBox1.addItem("Électroménager");
    }
}
    private void btnFiltrerActionPerformed(java.awt.event.ActionEvent evt) {
    String categorie = (String) jComboBox1.getSelectedItem();
    java.util.Date dateDebut = (java.util.Date) jSpinner1.getValue();
    java.util.Date dateFin = (java.util.Date) jSpinner2.getValue();
    
    java.util.Calendar calDebut = java.util.Calendar.getInstance();
    calDebut.setTime(dateDebut);
    calDebut.set(java.util.Calendar.HOUR_OF_DAY, 0);
    calDebut.set(java.util.Calendar.MINUTE, 0);
    calDebut.set(java.util.Calendar.SECOND, 0);
    
    java.util.Calendar calFin = java.util.Calendar.getInstance();
    calFin.setTime(dateFin);
    calFin.set(java.util.Calendar.HOUR_OF_DAY, 23);
    calFin.set(java.util.Calendar.MINUTE, 59);
    calFin.set(java.util.Calendar.SECOND, 59);
    
    java.sql.Date sqlDateDebut = new java.sql.Date(calDebut.getTimeInMillis());
    java.sql.Date sqlDateFin = new java.sql.Date(calFin.getTimeInMillis());
    
    java.util.List<Vente> resultats;
    
    if (categorie == null || categorie.equals("Toutes")) {
        resultats = venteService.findByPeriode(sqlDateDebut, sqlDateFin);
    } else {
        resultats = venteService.findByCategorieAndPeriode(categorie, sqlDateDebut, sqlDateFin);
    }
    
    afficherResultats(resultats);
}
    private void btnReinitialiserActionPerformed(java.awt.event.ActionEvent evt) {
    jComboBox1.setSelectedIndex(0);
    jSpinner1.setValue(new java.util.Date());
    java.util.Calendar cal = java.util.Calendar.getInstance();
    cal.add(java.util.Calendar.DAY_OF_MONTH, 30);
    jSpinner2.setValue(cal.getTime());
    
    java.util.List<Vente> toutes = venteService.findAll();
    afficherResultats(toutes);
}
    private void afficherResultats(java.util.List<Vente> ventes) {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable2.getModel();
    model.setRowCount(0);
    
    for (Vente v : ventes) {
        String clientNom = "Client " + v.getIdClient();
        String produitNom = "Produit " + v.getIdProduit();
        
        try {
            boutique.entities.Client c = clientService.findById(v.getIdClient());
            if (c != null) clientNom = c.getNom();
            
            boutique.entities.Produit p = produitService.findById(v.getIdProduit());
            if (p != null) produitNom = p.getLibelle();
        } catch (Exception e) {}
        
        model.addRow(new Object[]{
            v.getIdVente(),
            v.getDateVente(),
            clientNom,
            produitNom,
            v.getQuantite()
        });
    }
    
    setTitle("Recherche par catégorie - " + ventes.size() + " résultat(s)");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
