/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boutique.ui;

import boutique.services.ProduitService;
import boutique.services.ClientService;
import boutique.services.VenteService;
import boutique.entities.Client;
import boutique.entities.Produit;
import boutique.entities.Vente;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import java.awt.FlowLayout;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.Calendar;
import javax.swing.JLabel;
import javax.swing.JButton;
import java.util.Date;



/**
 *
 * @author hp
 */
public class VenteForm extends javax.swing.JInternalFrame {
    private VenteService venteService = new VenteService();
    private ClientService clientService = new ClientService();
    private ProduitService produitService = new ProduitService();


    /**
     * Creates new form VenteFrame
     */
    public VenteForm() {
        initComponents();
      tableVentes.setFillsViewportHeight(true);
    tableVentes.setAutoResizeMode(tableSuivi.AUTO_RESIZE_ALL_COLUMNS);
    jScrollPane2.setPreferredSize(new java.awt.Dimension(2000,1000));

        setSize(1000, 700);
        setTitle("Gestion des Ventes");

        loadClients();
        loadProduits();
        loadTableVentes();
        loadSuiviVentes();

    }
    private void initTableSuivi() {
    tableSuivi.setModel(new DefaultTableModel(
        new Object[]{"IdProduit", "Produit", "Total vendu"},
        0
    ));
}
private void refreshSuiviParProduit() {
    DefaultTableModel model = (DefaultTableModel) tableSuivi.getModel();
    model.setRowCount(0);

    try {
        List<Object[]> rows = venteService.venteParProduit(); 
        for (Object[] r : rows) {
            model.addRow(r);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
    }
}


private void loadClients() {
    ComboClient.removeAllItems();
    List<Client> clients = clientService.findAll();
    for (Client c : clients) {
        ComboClient.addItem(c.getIdClient() + " - " + c.getNom());
    }
}
private void loadProduits() {
    ComboProduit.removeAllItems();
    List<Produit> produits = produitService.findAll();
    for (Produit p : produits) {
        ComboProduit.addItem(p.getIdProduit() + " - " + p.getLibelle());
    }
}
private void loadTableVentes() {
    DefaultTableModel model = (DefaultTableModel) tableVentes.getModel();
    model.setRowCount(0);

    List<Vente> ventes = venteService.findAll();
    for (Vente v : ventes) {
        model.addRow(new Object[]{
            v.getIdVente(),
            v.getDateVente(),
            v.getIdClient(),
            v.getIdProduit(),
            v.getQuantite(),
            });
                    
    }
                }

private void loadSuiviVentes() {

    DefaultTableModel model = (DefaultTableModel) tableSuivi.getModel();
    model.setRowCount(0);

    for (Object[] row : venteService.venteParProduit()) {
        model.addRow(row);
    }
}

    private int getIdFromCombo(javax.swing.JComboBox combo) {
    String s = combo.getSelectedItem().toString();
    return Integer.parseInt(s.split(" - ")[0]);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelVentes = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblIdVente1 = new javax.swing.JLabel();
        lblClient1 = new javax.swing.JLabel();
        lblProduit1 = new javax.swing.JLabel();
        lblQuantite1 = new javax.swing.JLabel();
        txtIdVente = new javax.swing.JTextField();
        ComboClient = new javax.swing.JComboBox();
        ComboProduit = new javax.swing.JComboBox();
        txtQuantite = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDateVente = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        btnVendre1 = new javax.swing.JButton();
        btnSupprimer1 = new javax.swing.JButton();
        btnVider1 = new javax.swing.JButton();
        btnRetour1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableVentes = new javax.swing.JTable();
        panelSuivi = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSuivi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));

        lblIdVente1.setText("IdVente :");

        lblClient1.setText("Client :");

        lblProduit1.setText("Produit :");

        lblQuantite1.setText("Quantite :");

        txtIdVente.setEditable(false);

        jLabel4.setText("Formulaire :");

        jLabel5.setText("DateVnte:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lblClient1)
                    .addComponent(lblProduit1)
                    .addComponent(lblQuantite1)
                    .addComponent(jLabel4)
                    .addComponent(lblIdVente1))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ComboClient, 0, 145, Short.MAX_VALUE)
                        .addComponent(ComboProduit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtQuantite)
                        .addComponent(txtDateVente))
                    .addComponent(txtIdVente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 541, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblIdVente1)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDateVente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClient1)
                            .addComponent(ComboClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProduit1)
                            .addComponent(ComboProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuantite1))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtIdVente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPanel6.add(jPanel7, gridBagConstraints);

        jPanel8.setBackground(new java.awt.Color(255, 255, 204));

        btnVendre1.setText("Vendre");
        btnVendre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendre1ActionPerformed(evt);
            }
        });

        btnSupprimer1.setText("Supprimer");
        btnSupprimer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimer1ActionPerformed(evt);
            }
        });

        btnVider1.setText("Vider");
        btnVider1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVider1ActionPerformed(evt);
            }
        });

        btnRetour1.setText("Retour");
        btnRetour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetour1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Actions :");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSupprimer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVendre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRetour1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(btnVendre1)
                .addGap(28, 28, 28)
                .addComponent(btnSupprimer1)
                .addGap(30, 30, 30)
                .addComponent(btnVider1)
                .addGap(27, 27, 27)
                .addComponent(btnRetour1)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 0);
        jPanel6.add(jPanel8, gridBagConstraints);

        tableVentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IdVente", "DateVente", "Client", "Produit", "Quantite"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVentesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableVentes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel6.add(jScrollPane3, gridBagConstraints);

        panelVentes.addTab("Ventes", jPanel6);

        tableSuivi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IdProduit", "Libelle", "TotalVentes", "Nbr Ventes", "Prix Total "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableSuivi);

        jLabel1.setText("les ventes par produit :");

        javax.swing.GroupLayout panelSuiviLayout = new javax.swing.GroupLayout(panelSuivi);
        panelSuivi.setLayout(panelSuiviLayout);
        panelSuiviLayout.setHorizontalGroup(
            panelSuiviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuiviLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelSuiviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(541, Short.MAX_VALUE))
        );
        panelSuiviLayout.setVerticalGroup(
            panelSuiviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuiviLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(722, Short.MAX_VALUE))
        );

        panelVentes.addTab("Suivi par produit", panelSuivi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentes, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentes)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVendre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendre1ActionPerformed

        try {
            if (ComboClient.getSelectedItem() == null || ComboProduit.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Choisissez un client et un produit !");
                return;
            }

            int idClient = getIdFromCombo(ComboClient);
            int idProduit = getIdFromCombo(ComboProduit);

            int qte = Integer.parseInt(txtQuantite.getText().trim());
            if (qte <= 0) {
                JOptionPane.showMessageDialog(this, "Quantité doit être > 0 !");
                return;
            }

            // 1) vérifier stock
        Produit p = produitService.findById(idProduit);
        if (p == null) {
            JOptionPane.showMessageDialog(this, "Produit introuvable !");
            return;
        }

        if (p.getStock() < qte) {
            JOptionPane.showMessageDialog(this,
                "Stock insuffisant ! Stock actuel = " + p.getStock());
            return;
        }

        // 2) enregistrer vente
        Vente v = new Vente();
        v.setDateVente(new java.sql.Date(System.currentTimeMillis())); // date auto
        v.setIdClient(idClient);
        v.setIdProduit(idProduit);
        v.setQuantite(qte);

        venteService.create(v);

        // 3) mise à jour stock
        p.setStock(p.getStock() - qte);
        produitService.update(p);

        JOptionPane.showMessageDialog(this, "Vente enregistrée !");
        loadTableVentes();
        loadSuiviVentes();
        clearForm();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Quantité invalide !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnVendre1ActionPerformed

    private void btnSupprimer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimer1ActionPerformed

        try {
            int id = Integer.parseInt(txtIdVente.getText().trim());
            venteService.delete(id);

            loadTableVentes();
            loadSuiviVentes();

            JOptionPane.showMessageDialog(this, "Vente supprimée ✅");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur suppression: " + e.getMessage());

        }
    }//GEN-LAST:event_btnSupprimer1ActionPerformed

    private void btnVider1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVider1ActionPerformed

        clearForm();
    }//GEN-LAST:event_btnVider1ActionPerformed

    private void btnRetour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetour1ActionPerformed
        MainForm mf = new MainForm();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRetour1ActionPerformed

    private void tableVentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVentesMouseClicked

        int selectedRow = tableVentes.getSelectedRow();

        if (selectedRow != -1) {

            txtIdVente.setText(tableVentes.getValueAt(selectedRow, 0).toString());
            txtDateVente.setText(tableVentes.getValueAt(selectedRow, 1).toString());

            // Pour Client et Produit (si tu utilises format "id - nom")
            int idClient = Integer.parseInt(tableVentes.getValueAt(selectedRow, 2).toString());
            int idProduit = Integer.parseInt(tableVentes.getValueAt(selectedRow, 3).toString());

            selectComboById(ComboClient, idClient);
            selectComboById(ComboProduit, idProduit);

            txtQuantite.setText(tableVentes.getValueAt(selectedRow, 4).toString());
        }
    }//GEN-LAST:event_tableVentesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboClient;
    private javax.swing.JComboBox ComboProduit;
    private javax.swing.JButton btnRetour1;
    private javax.swing.JButton btnSupprimer1;
    private javax.swing.JButton btnVendre1;
    private javax.swing.JButton btnVider1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblClient1;
    private javax.swing.JLabel lblIdVente1;
    private javax.swing.JLabel lblProduit1;
    private javax.swing.JLabel lblQuantite1;
    private javax.swing.JPanel panelSuivi;
    private javax.swing.JTabbedPane panelVentes;
    private javax.swing.JTable tableSuivi;
    private javax.swing.JTable tableVentes;
    private javax.swing.JTextField txtDateVente;
    private javax.swing.JTextField txtIdVente;
    private javax.swing.JTextField txtQuantite;
    // End of variables declaration//GEN-END:variables
private void selectComboById(JComboBox combo, int id) {
    for (int i = 0; i < combo.getItemCount(); i++) {
        String item = combo.getItemAt(i).toString(); // "id - nom"
        int itemId = Integer.parseInt(item.split(" - ")[0].trim());
        if (itemId == id) {
            combo.setSelectedIndex(i);
            return;
        }
    }
}
    
    private void clearForm() {
    txtIdVente.setText("");
    txtDateVente.setText("");
    txtQuantite.setText("");

    if (ComboClient.getItemCount() > 0) ComboClient.setSelectedIndex(0);
    if (ComboProduit.getItemCount() > 0) ComboProduit.setSelectedIndex(0);
}
}

